name: terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev | qa | prod'
        required: true
        default: 'prod'

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Init
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform init
      - name: Plan
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"
      - name: Manual approval gate
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
      - name: Apply
        if: ${{ success() }}
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
